# Generated by Django 5.0.2 on 2024-03-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('proveedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Compra.proveedor')),
                ('nombre_mayorista', models.CharField(max_length=100)),
            ],
            bases=('Compra.proveedor',),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
