# Generated by Django 5.0.2 on 2024-03-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0004_mayorista_proveedor_cuil_alter_proveedor_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='cuil',
        ),
        migrations.CreateModel(
            name='ProveedorMinorista',
            fields=[
                ('proveedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Compra.proveedor')),
            ],
            bases=('Compra.proveedor',),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProveedorMayorista',
            fields=[
                ('proveedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Compra.proveedor')),
                ('tipo_proveedor', models.CharField(max_length=100)),
                ('cuil', models.CharField(max_length=20)),
            ],
            bases=('Compra.proveedor',),
        ),
        migrations.DeleteModel(
            name='Mayorista',
        ),
    ]
