# Generated by Django 5.0.2 on 2024-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0005_remove_proveedor_cuil_proveedorminorista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedorminorista',
            name='proveedor_ptr',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista')], default='minorista', max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProveedorMayorista',
        ),
        migrations.DeleteModel(
            name='ProveedorMinorista',
        ),
    ]
