# Generated by Django 5.0.2 on 2024-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0006_remove_proveedorminorista_proveedor_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
