# Generated by Django 5.0.2 on 2024-03-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0007_remove_proveedor_categoria_remove_proveedor_cuil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
