# Generated by Django 5.0.2 on 2024-04-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
