# Generated by Django 5.0.2 on 2024-03-13 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_termino',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
